from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError
import re
import json
import os
from datetime import datetime
from pathlib import Path
from copy import copy
from openpyxl import Workbook, load_workbook

HOTEL_URL = "https://www.tajhotels.com/en-in/hotels/taj-city-centre-gurugram?adults=1&children=0&from=2026-12-25&to=2026-12-26"
TAJ_API_HOST = "api-cug1-825v2.tajhotels.com"
TAJ_API_PATH = "/hudiniService/v1/hotel-availability"

ROOM_NAMES = [
    "SUPERIOR ROOM TWIN BED",
    "SUPERIOR ROOM KING BED",
]
TARGET_ROOM_CODES = {
    "DTX": "SUPERIOR ROOM TWIN BED",
    "DKX": "SUPERIOR ROOM KING BED",
}
TELEGRAM_CHAT_ID = "348797661"
EXCEL_FILE = Path("Taj_Price_History.xlsx")


def create_browser(p):
    print("Fresh headless browser open kar raha hoon...")
    browser = p.chromium.launch(
        headless=True,
        args=[
            "--no-sandbox",
            "--disable-setuid-sandbox",
            "--disable-dev-shm-usage",
            "--disable-gpu",
            "--no-first-run",
            "--no-default-browser-check",
            "--deny-permission-prompts",
        ],
    )
    context = browser.new_context(
        viewport={"width": 1400, "height": 900},
        locale="en-IN",
        timezone_id="Asia/Kolkata",
        permissions=[],
    )
    page = context.new_page()
    page.set_default_timeout(60000)
    return browser, context, page


def is_target_availability_response(response):
    return (
        response.request.method == "POST"
        and TAJ_API_HOST in response.url
        and TAJ_API_PATH in response.url
    )


def wait_for_availability_response(page):
    captured = {"data": None, "status": None, "url": None}

    def on_response(response):
        if not is_target_availability_response(response):
            return
        try:
            request_data = response.request.post_data
            if request_data:
                req = json.loads(request_data)
                if req.get("startDate") != "2026-12-25" or req.get("endDate") != "2026-12-26":
                    return
            if response.status != 200:
                print("Taj availability response HTTP:", response.status)
                return
            body = response.text()
            data = json.loads(body)
            captured["data"] = data
            captured["status"] = response.status
            captured["url"] = response.url
            print("Taj availability API response captured: HTTP 200")
        except Exception as exc:
            print("Availability response parse error:", exc)

    page.on("response", on_response)
    return captured


def click_search(page):
    print("Taj SEARCH button trigger kar raha hoon...")

    # The hotel page accepts the stay dates through the URL query parameters.
    # Clicking SEARCH is what actually causes the browser to request the
    # hotel-availability API. No calendar DOM selectors are used here.
    candidates = [
        page.get_by_role("button", name=re.compile(r"^SEARCH$", re.I)),
        page.get_by_text(re.compile(r"^SEARCH$", re.I)),
    ]

    for locator in candidates:
        try:
            count = locator.count()
            for i in range(min(count, 20)):
                el = locator.nth(i)
                if not el.is_visible():
                    continue
                try:
                    el.scroll_into_view_if_needed(timeout=5000)
                except Exception:
                    pass
                print("SEARCH button mil gaya; click kar raha hoon.")
                el.click(timeout=10000)
                return True
        except Exception as exc:
            print("SEARCH locator attempt failed:", exc)

    # Last-resort: inspect visible buttons and click one whose text is SEARCH.
    buttons = page.locator("button, [role='button']")
    for i in range(buttons.count()):
        try:
            el = buttons.nth(i)
            if not el.is_visible():
                continue
            txt = re.sub(r"\s+", " ", el.inner_text()).strip().upper()
            if txt == "SEARCH":
                print("SEARCH button fallback se mila; click kar raha hoon.")
                el.click(timeout=10000)
                return True
        except Exception:
            pass

    return False


def get_taj_api_response(page):
    captured = wait_for_availability_response(page)

    print("Taj hotel page load kar raha hoon...")
    page.goto(HOTEL_URL, wait_until="domcontentloaded", timeout=60000)
    page.wait_for_timeout(5000)
    print("Hotel page loaded:", page.url)

    # Search must be explicitly triggered. This reproduces the action that
    # produced the successful API request in the user's real Chrome capture.
    clicked = click_search(page)
    if not clicked:
        raise RuntimeError("Taj SEARCH button nahi mila; availability request trigger nahi hui.")

    # Wait for the API response generated by SEARCH.
    for _ in range(60):
        if captured["data"] is not None:
            break
        page.wait_for_timeout(1000)

    if captured["data"] is None:
        raise RuntimeError("Taj availability API response capture nahi hui after SEARCH.")

    Path("taj_last_api_response.json").write_text(
        json.dumps(captured["data"], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return captured["data"]


def api_price(rate):
    try:
        return float(rate["daily"][0]["price"]["amount"])
    except Exception:
        return None


def rate_is_100pct_nonrefundable(rate):
    rc = rate.get("rateContent") or {}
    details = rc.get("details") or {}
    bp = rate.get("bookingPolicy") or {}
    cp = rate.get("cancellationPolicy") or {}
    parts = [
        rc.get("name"),
        details.get("description"),
        details.get("detailedDescription"),
        details.get("displayName"),
        details.get("displayDescription"),
        bp.get("description"),
        bp.get("refundableStay"),
        cp.get("description"),
    ]
    text = re.sub(r"\s+", " ", " ".join(str(x) for x in parts if x)).upper()
    return (
        ("100 PCT" in text or "100%" in text or "100 PERCENT" in text)
        and ("NON-REFUNDABLE" in text or "NON REFUNDABLE" in text or "NONREFUNDABLE" in text)
    )


def extract_api_rates(data):
    results = {name: {"member": None, "standard": None} for name in ROOM_NAMES}
    room_rates = (data.get("roomAvailability") or {}).get("roomRates") or []

    for room in room_rates:
        room_name = TARGET_ROOM_CODES.get(room.get("roomCode"))
        if not room_name:
            continue

        # Prefer the room rates exactly for the target category. Ignore rates
        # whose card is explicitly 100% full-stay non-refundable.
        for rate in room.get("rooms") or []:
            if rate_is_100pct_nonrefundable(rate):
                print(
                    room_name, "|", rate.get("rateCode"),
                    "-> 100% full-stay non-refundable EXCLUDED",
                )
                continue

            member = api_price(rate.get("memberRate"))
            standard = api_price(rate.get("standardRate"))
            if member is not None and results[room_name]["member"] is None:
                results[room_name]["member"] = member
            if standard is not None and results[room_name]["standard"] is None:
                results[room_name]["standard"] = standard

            if results[room_name]["member"] is not None and results[room_name]["standard"] is not None:
                break

        print(
            room_name,
            "| Member:", results[room_name]["member"],
            "| Standard:", results[room_name]["standard"],
        )

    return results


def save_price_history(results, lowest, lowest_room, lowest_type):
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    if EXCEL_FILE.exists():
        wb = load_workbook(EXCEL_FILE)
        ws = wb.active
    else:
        wb = Workbook()
        ws = wb.active
        ws.title = "Price History"
        ws.append([
            "Date & Time",
            "Twin Member",
            "Twin Standard",
            "King Member",
            "King Standard",
            "Lowest Price",
            "Lowest Room",
            "Lowest Rate Type",
        ])

    twin = results.get("SUPERIOR ROOM TWIN BED") or {}
    king = results.get("SUPERIOR ROOM KING BED") or {}
    ws.append([
        now,
        twin.get("member"),
        twin.get("standard"),
        king.get("member"),
        king.get("standard"),
        lowest,
        lowest_room,
        str(lowest_type).upper(),
    ])

    for cell in ws[1]:
        font = copy(cell.font)
        font.bold = True
        cell.font = font

    widths = {"A": 20, "B": 15, "C": 15, "D": 15, "E": 15, "F": 15, "G": 30, "H": 18}
    for col, width in widths.items():
        ws.column_dimensions[col].width = width

    wb.save(EXCEL_FILE)
    print("Excel history saved:", EXCEL_FILE)


def send_telegram(message):
    import urllib.parse
    import urllib.request

    token = os.environ.get("TAJ_TELEGRAM_BOT_TOKEN", "").strip()
    if not token:
        print("Telegram token nahi mila; Telegram skip.")
        return False

    url = "https://api.telegram.org/bot" + token + "/sendMessage"
    data = urllib.parse.urlencode({"chat_id": TELEGRAM_CHAT_ID, "text": message}).encode("utf-8")
    try:
        req = urllib.request.Request(url, data=data, method="POST")
        with urllib.request.urlopen(req, timeout=20) as response:
            response.read()
        print("Telegram message sent.")
        return True
    except Exception as exc:
        print("Telegram send error:", exc)
        return False


def check_price(p):
    browser = context = page = None
    try:
        print("\n" + "=" * 65)
        print("TAJ CITY CENTRE GURUGRAM PRICE TRACKER - CLOUD CHECK")
        print("=" * 65)
        print("Dates     : 25 Dec 2026 -> 26 Dec 2026")
        print("Guests    : 1 | Rooms: 1")
        print("Method    : BROWSER SEARCH -> TAJ AVAILABILITY API RESPONSE")
        print("Telegram  : Enabled")
        print("=" * 65)

        browser, context, page = create_browser(p)
        data = get_taj_api_response(page)
        results = extract_api_rates(data)

        valid_prices = []
        for room_name, room_data in results.items():
            for rate_type in ("member", "standard"):
                value = room_data.get(rate_type)
                if value is not None:
                    valid_prices.append((value, room_name, rate_type))

        if not valid_prices:
            raise RuntimeError("Superior Twin/King ke liye koi valid price nahi mila.")

        lowest, lowest_room, lowest_type = min(valid_prices, key=lambda x: x[0])

        print("\n" + "=" * 65)
        print("LOWEST PRICE : ₹{:,.0f} / night".format(lowest))
        print("ROOM         :", lowest_room)
        print("RATE TYPE    :", lowest_type.upper())
        print("=" * 65)

        lines = [
            "💰 ₹{:,.0f} / NIGHT".format(lowest),
            "LOWEST PRICE",
            "",
            "🏨 Taj City Centre Gurugram",
            "📅 25 Dec 2026 → 26 Dec 2026",
            "👤 1 Guest | 1 Room",
            "",
        ]
        for room_name in ROOM_NAMES:
            d = results.get(room_name) or {}
            lines.append("🛏 " + room_name)
            lines.append(
                "Member Rate: ₹{:,.0f} / night".format(d["member"])
                if d.get("member") is not None else "Member Rate: Not available"
            )
            lines.append(
                "Standard Rate: ₹{:,.0f} / night".format(d["standard"])
                if d.get("standard") is not None else "Standard Rate: Not available"
            )
            lines.append("")
        lines.append("❌ 100% full-stay non-refundable rate cards excluded")
        lines.append("🔗 " + HOTEL_URL)
        message = "\n".join(lines)

        save_price_history(results, lowest, lowest_room, lowest_type)
        send_telegram(message)
        return True

    finally:
        for obj in (page, context, browser):
            try:
                if obj:
                    obj.close()
            except Exception:
                pass
        print("Browser closed.")


with sync_playwright() as p:
    ok = check_price(p)
    if not ok:
        raise SystemExit(1)
